---
- name: Install unzip
  apt: pkg=unzip state=present

- name: Downloading consul binary from official repo .
  get_url: url={{ consul_binary_link }} dest=/tmp/consul.zip mode=0777

- name: extract to /usr/local/bin/.
  command: unzip /tmp/consul.zip -d /usr/local/bin/
  async: 1

- name: Change permission
  file: path=/usr/local/bin/consul mode=0655

- name: creating consul.d
  file: path=/etc/consul.d state=directory

- name: assigning permission for consul.d
  file:
    path: /etc/consul.d
    mode: u=rwX,g=rwX,o=rwX